accumulate_grad_batches: 1
adam_epsilon: 1.0e-08
amp_level: O1
atomic: true
auto_lr_find: false
auto_scale_batch_size: false
auto_select_gpus: false
benchmark: false
cache_dir: ''
check_val_every_n_epoch: 1
checkpoint_callback: true
config_name: ''
data_dir: ../../data/atomic2020
default_root_dir: null
deterministic: false
distributed_backend: null
do_predict: true
do_train: true
early_stop_callback: false
eval_batch_size: 32
fast_dev_run: false
fp16: false
fp16_opt_level: O2
freeze_embeds: false
freeze_encoder: false
gpus: 1
gradient_clip_val: 0
learning_rate: 1.0e-05
limit_test_batches: 1.0
limit_train_batches: 1.0
limit_val_batches: 1.0
log_gpu_memory: null
log_save_interval: 100
logger: true
logger_name: default
max_epochs: 1
max_source_length: 48
max_steps: null
max_target_length: 24
min_epochs: 1
min_steps: null
model_name_or_path: facebook/bart-large
n_test: -1
n_train: -1
n_val: 100
num_nodes: 1
num_processes: 1
num_sanity_val_steps: 2
num_workers: 2
output_dir: ./results/
overfit_batches: 0.0
overfit_pct: null
precision: 32
prepare_data_per_node: true
print_nan_grads: false
process_position: 0
profiler: null
progress_bar_refresh_rate: 1
reload_dataloaders_every_epoch: false
replace_sampler_ddp: true
resume_from_checkpoint: null
row_log_interval: 50
seed: 42
sortish_sampler: true
src_lang: ''
task: summarization
terminate_on_nan: false
test_checkpoint: ./results/val_avg_rouge2=0.0094-step_count=2.ckpt
test_max_target_length: 24
test_percent_check: null
tgt_lang: ''
tokenizer_name: null
tpu_cores: null
track_grad_norm: -1
train_batch_size: 32
train_percent_check: null
truncated_bptt_steps: null
val_check_interval: 1.0
val_max_target_length: 24
val_percent_check: null
warmup_steps: 0
weight_decay: 0.0
weights_save_path: null
weights_summary: top
